js.tv.itc.cn

vas.pptv.com
jp.as.pptv.com
static.g.pptv.com
ios.synacast.com
android.config.synacast.com
ol.synacast.com
ads.data.pplive.com
asimgs.pplive.cn

de.as.pptv.com
ads.aplus.pptv.com
ik.synacast.com
s1.pplive.cn

mobads-static.baidu.com
jntinchina.com

ark.letv.com
dc.letv.com
le.so.letv.com
i0.letvimg.com
i1.letvimg.com
i3.letvimg.com
rvs.letv.com
fz.letv.com

bs.da.hunantv.com
fp.da.hunantv.com
x.da.hunantv.com

#mmbiz.qlogo.cn
adstatic.chinaso.com
statis.api.3g.youku.com
bs.da.hunantv.com
ad.api.3g.tudou.com
agn.aty.sohu.com
mmg.aty.sohu.com
n.mark.letv.com
irs01.com
g.cn.miaozhen.com
lives.l.qq.com
vqq.admaster.com.cn
acs.56.com
stat.v-56.com
msg.ua.56.com
acs.stat.v-56.com
mad.stat.v-56.com
so.stat.v-56.com
stat2.corp.v-56.com
stat2.stat.v-56.com
stat3.corp.v-56.com
stat3.stat.v-56.com
stat4.stat.v-56.com
t4u.stat.v-56.com
api.cupid.iqiyi.com
msg.71.am
msga.71.am
afp.qiyi.com
msg.video.qiyi.com
msg2.video.qiyi.com
track.cupid.qiyi.com
a.ckm.iqiyi.com
ad.m.iqiyi.com
c.uaa.iqiyi.com
cloudpush.iqiyi.com
cmts.iqiyi.com
data.store.iqiyi.com
feedback.iqiyi.com
l.rcd.iqiyi.com
mbdapp.iqiyi.com
mbdlog.iqiyi.com
mixer.cupid.iqiyi.com
msg.iqiyi.com
nl.rcd.iqiyi.com
store.iqiyi.com
terren.cntv.cn
a.cctv.com
a.cntv.cn
ad.cctv.com
d.cntv.cn
log.vdn.apps.cntv.cn
adguanggao.eee114.com
cctv.adsunion.com
js.bmgad.com
med.soodao.com
click.hunantv.com
corp.hunantv.com
flv.res.hunantv.com
log.hunantv.com
log.v2.hunantv.com
mobile.log.hunantv.com
x.da.hunantv.com
stat.titan.imgo.tv
click.hifly.tv
hunantv.m.cn.miaozhen.com
recv-vd.gridsumdissector.cn
recv-vd.gridsumdissector.com
geo.gridsumdissector.com
analytics.ku6.com
pq.stat.ku6.com
st.vq.ku6.cn
v0.stat.ku6.com
v1.stat.ku6.com
v2.stat.ku6.com
v3.stat.ku6.com
v4.stat.ku6.com
v5.stat.ku6.com
v6.stat.ku6.com
stat0.888.ku6.com
stat1.888.ku6.com
stat2.888.ku6.com
stat3.888.ku6.com
ark.letv.com
g.q4ik.com
fz.letv.com
dc.letv.com
plog.dc.letv.com
dev.dc.letv.com
pro.letv.com
pro.hoye.letv.com
stat.letv.com
asimgs.pplive.cn
ads.data.pplive.com
afp.pplive.com
afv.pplive.com
caipiao.pplive.com
dh.pplive.com
g.pplive.com
ins-stat.pplive.com
ins-version.pplive.com
ins.pplive.com
live.v2.pplive.com
pp1.pplive.com
pp2.as.pplive.cn
up.pplive.com
as.aplus.pptv.com
de.as.pptv.com
dl4.vas.pptv.com
g.pptv.com
ga.pptv.com
iafp.pptv.com
jp.as.pptv.com
pp2.pptv.com
ppsj.pptv.com
static.g.pptv.com
tips.passport.pptv.com
tj.g.pptv.com
vas.aplus.pptv.com
wafp.pptv.com
way.pptv.com
wstat.pptv.com
zt.pptv.com
h.g1d.net
p.g1d.net
ppva.g1d.net
video-va.g1d.net
aty.tv.sohu.com
atyt.tv.sohu.com
click2.hd.sohu.com
count.vrs.sohu.com
ctr.hd.sohu.com
dev.app.yule.sohu.com
game.m.sohu.com
m.aty.sohu.com
p.aty.sohu.com
pb.hd.sohu.com
pg.aty.sohu.com
pv.hd.sohu.com
stat.m.tv.sohu.com
upgrade.m.tv.sohu.com
v.aty.sohu.com
vg.aty.sohu.com
vm.aty.sohu.com
click.hd.sohu.com.cn
mb.hd.sohu.com.cn
pb.hd.sohu.com.cn
ad.api.3g.youku.com
ad.atm.youku.com
api.gamex.mobile.youku.com
atm.youku.com
c.miaozhen.atm.youku.com
cm.miaozhen.atm.youku.com
count.atm.youku.com
dl.m.youku.com
e.stat.youku.com
fvid.atm.youku.com
html.atm.youku.com
lstat.youku.com
mf.atm.youku.com
mi.atm.youku.com
mp.atm.youku.com
n.miaozhen.atm.youku.com
p-log.ykimg.com
passport-log.youku.com
push.m.youku.com
rec.api.gamex.mobile.youku.com
stat.youku.com
static.atm.youku.com
td.atm.youku.com
test.gamex.mobile.youku.com
urchin.lstat.youku.com
v2html.atm.youku.com
valb.atm.youku.com
valc.atm.youku.com
valf.atm.youku.com
valo.atm.youku.com
valp.atm.youku.com
vhtml.atm.youku.com
vhtml.youku.com
vid.atm.youku.com
walp.atm.youku.com
adcontrol.tudou.com
adextensioncontrol.tudou.com
adplay.tudou.com
erreport.tudou.com
istat.tudou.com
iwstat.tudou.com
logs.live.tudou.com
nstat.tudou.com
pl.pb.ops.tudou.com
player.pb.ops.tudou.com
stat.tudou.com
stats.tudou.com
tdap.tudou.com
tdcm.tudou.com
tvp.tudou.com
union.tudou.com
wwwtest.tudou.com
tudouflv.dnion.com
video.mpush.qq.com
aid.video.qq.com
c.l.qq.com
livep.l.qq.com
livew.l.qq.com
news.l.qq.com
p.l.qq.com
t.l.qq.com
rlog.video.qq.com
la.gtimg.com
pgdt.gtimg.cn
gstatic.com
googleadservices.com
googleadsserving.cn
googlepages.com
googlesyndication.com
1133.cc
37cs.com
51.la
51yes.com
acs86.com
adpolestar.net
adpower.cn
adsame.com
allyes.cn
allyes.com
atdmt.com
chanet.com.cn
clickeye.com.cn
cnxad.com
doubleclick.net
heima8.com
imrworldwide.com
keyrun.com
lianmeng.com
linezing.com
mediaplex.com
mediav.com
miaozhen.com
myad.cn
oadz.com
onetad.com
sandai.net
wauee.com
wrating.com
yigao.com
yiqifa.com
zedo.com
11.mydrivers.com
g.crsky.com
gimg.iqilu.com
images.sohu.com
c.isdspeed.qq.com
wup.imtt.qq.com
bs.baidu.com


address=/v.gdt.qq.com/127.0.0.1
address=/c.gdt.qq.com/127.0.0.1
address=/q.i.gdt.qq.com/127.0.0.1
address=/s.gdt.qq.com/127.0.0.1
address=/hm.l.qq.com/127.0.0.1
address=/livew.l.qq.com/127.0.0.1
address=/lives.l.qq.com/127.0.0.1
address=/livep.l.qq.com/127.0.0.1
address=/livec.l.qq.com/127.0.0.1
address=/w.l.qq.com/127.0.0.1
address=/c.l.qq.com/127.0.0.1
address=/redirect.simba.taobao.com/127.0.0.1
gdown.baidu.com
address=/dup.baidustatic.com/127.0.0.1
address=/cpro.baidustatic.com/127.0.0.1
address=/rigel.baidustatic.com/127.0.0.1
address=/ubmcmm.baidustatic.com/127.0.0.1
address=/cpro2.baidustatic.com/127.0.0.1


agn.aty.sohu.com
pv.hd.sohu.com

ugcws.video.gtimg.com
ugcws.video.gtimg.com.wscdns.com
qqhttp.ddwscache.ourdvs.com
www.ipswitch.ourdvs.com
sec.video.qq.com
mmbiz.qpic.cn

ac.o2.qq.com
ra.gtimg.com
vamaker.com
msg.71.am
bce.baidu-mgame.com

手机wifi检测
connectivitycheck.gstatic.com
connectivitycheck.android.com/generate204
